# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'This will be shown as the title of notification and announcement', max_length=32)),
                ('message', models.CharField(help_text=b'The message you want to convey', max_length=200)),
                ('date_time_to_publish', models.DateTimeField(help_text=b'Schedule date and time for announcement', verbose_name=b'datetime publish')),
                ('date_time_expire', models.DateTimeField(help_text=b'Expiry date and time for announcement', verbose_name=b'datetime expire')),
                ('groups', models.ManyToManyField(to=b'auth.Group')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
