# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20180604_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annoucements',
            old_name='date_expire',
            new_name='date_time_expire',
        ),
        migrations.RenameField(
            model_name='annoucements',
            old_name='date_published',
            new_name='date_time_published',
        ),
        migrations.AlterField(
            model_name='annoucements',
            name='title',
            field=models.CharField(help_text=b'Tit', max_length=100),
        ),
    ]
