# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20180604_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucements',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annoucements',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annoucements',
            name='date_time_expire',
            field=models.DateTimeField(help_text=b'The date and time you want the announcement to expire', verbose_name=b'datetime expire'),
        ),
        migrations.AlterField(
            model_name='annoucements',
            name='date_time_published',
            field=models.DateTimeField(help_text=b'The date and time you want to schedule announcement/notification', verbose_name=b'datetime published'),
        ),
        migrations.AlterField(
            model_name='annoucements',
            name='message',
            field=models.CharField(help_text=b'The message you want to convey', max_length=200),
        ),
        migrations.AlterField(
            model_name='annoucements',
            name='title',
            field=models.CharField(help_text=b'This will be shown as the title of notification and announcement', max_length=32),
        ),
    ]
