# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20180604_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annoucements',
            old_name='created_date',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='annoucements',
            old_name='modified_date',
            new_name='updated',
        ),
    ]
