# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_auto_20180604_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucements',
            new_name='Announcements',
        ),
    ]
