# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20180604_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='date_time_published',
        ),
    ]
